<?php

namespace Ahe\gsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneFraisHorsForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisHorsForfaitRepository extends EntityRepository {

    public function findAllById($idVisiteur) {
        $res = $this->getEntityManager()->createQueryBuilder('SELECT a.id from LigneFraisHorsForfait a where idVisiteur = :visiteur')
                
                ->setParameter('visiteur', $idVisiteur);
        return $res->getQuery()->getResult();
    }

}
