<?php

namespace Ahe\gsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneFraisForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneFraisForfaitRepository extends EntityRepository
{

    public function findAllById($idVisiteur) {
        $res = $this->createQueryBuilder()
                ->add('select','a')
                ->where('c.idVisiteur',':visiteur')
                ->setParameter('visiteur', $idVisiteur);
        return $res->getQuery()->getResult();
                
       
      
        
    }
}
